config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :comments
  resources :users do
    resources :adventures 

  end
  

  root 'adventures#index'
  

  controller :comments do
    post "comment" => :create
  end
  
  resources :adventures do
    resources :comments
  end

end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
  mount_uploader :video, VideoUploader
  belongs_to :user

  has_many :comments
  has_attached_file :image, :styles => { :small=> '50x50>',:medium => '300x300>', :thumb => '100x100>'}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :adventure
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  # attr_accessor   :password, :password_confirmation
   has_many :adventures, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :adventures, dependent: :destroy
  has_many :comments 
>>>>>>> master
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :set_adventure, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :index]
  before_action :authenticate_user!

  # GET /adventures
  # GET /adventures.json
  def index
    @adventures = current_user.adventures
  end

  # GET /adventures/1
  # GET /adventures/1.json
  def show

    # @adventure = @current_user.adventures(params[:user_id])
    # @adventure = Adventure.find(params[:user_id])

    @adventures = current_user.adventures.find(params[:id])

  end

  # GET /adventures/new
  def new
    @adventure = Adventure.new(params[:adventure])
  end


  # GET /adventures/1/edit
  def edit
    @adventure = Adventure.find(params[:id])
  end

  # POST /adventures
  # POST /adventures.json
  def create
    @adventure = Adventure.new(adventure_params)

    @adventure.user= current_user
    respond_to do |format|
      if @adventure.save
        format.html { redirect_to user_adventures_path, notice: 'Adventure was successfully created.' }

    
      else
        format.html { render :new }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adventures/1
  # PATCH/PUT /adventures/1.json
  def update
    @adventure = Adventure.find(params[:id])
    respond_to do |format|
      if @adventure.update(adventure_params)

        flash[:notice] = 'Adventure was successfully updated.'
        format.html { redirect_to user_adventure_path }
        format.xml  { head :ok }
      else
        format.html { render :edit }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adventures/1
  # DELETE /adventures/1.json
  def destroy
    @adventure.destroy
    respond_to do |format|
      format.html { redirect_to adventures_url, notice: 'Adventure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_adventure
    @adventure = current_user.adventures.find(params[:id])
  end

  def set_user
    @user = current_user
  end
    
  # Never trust parameters from the scary internet, only allow the white list through.
  def adventure_params
    params.require(:adventure).permit(:place, :description, :image, :title, :video, :user_id, :body)
  end
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
 
    def create
      @adventure = Adventure.find(params[:adventure_id])
      @comment = @adventure.comments.create(comment_params)
      if @comment.save
        flash[:notice] = "Comment has been created."
        redirect_to @adventure
      else
        flash.now[:danger] = "error"
      end
    end 

    def comment_params
      params.require(:comment).permit(:body, :email)
    end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
    
  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
     @user = User.find(params[:id])
     @adventures = @user.adventures.paginate(page: params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
          # sign_in @user
         redirect_to @user, :flash => { :success => "Welcome to the MyAdventure App!" }
      else
        render 'new'
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
     # @user = User.find(params[:id])
     @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :adventure, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adventures/_form.html.erb
<%= form_for @adventure, url: user_adventures_path, html: {multipart: true} do |f| %>

  <% if @adventure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>
      <ul>
        <% @adventure.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class='field'>
    <%= f.label :title, 'Title:' %>
    <%= f.text_field :title, :placholder => 'Title' %>
  </div>

  <div class='field'>
    <%= f.label :place, 'Place:' %>
    <%= f.text_field :place, :placholder => 'Place' %>
  </div>

  <div class='field'>
    <%= f.label :description, 'Description:' %>
    <%= f.text_field :description, :placholder => 'Name' %>
  </div>

  <div class='field'>
    <%= f.label :image, 'Image:' %>
    <%= f.file_field :image, :placholder => 'image' %>
  </div>
  
  <div class='field'>
    <%= f.label :video, 'Video:' %>
    <%=f.file_field :video%>
  </div>
  
  <div class='actions'>
    <%= f.submit :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/adventures/edit.html.erb
<h1>Editing Adventure</h1>

<%= form_for @adventure, url: user_adventure_path, html: {multipart: true} do |f| %>
  <%= render 'form' %>
<% end %>

app/views/adventures/index.html.erb
<h1>Listing Adventures</h1>
<table>
  <div class='main'>
    <table class="table table-striped">
      <th>Title</th>
      <th>Place</th>
      <th>Descrption</th>
      <th>Image</th>
      <th>Video</th>
      <th colspan="3"></th>
      <tbody>
        <% @adventures.each do |adventure| %>
          <tr>
            <td><%= adventure.title %></td>
            <td><%= adventure.place %></td>
            <td><%= adventure.description %></td>
            <td><%= image_tag adventure.image.url(:thumb) %></td>
            <td><%= video_tag adventure.video_url.to_s, :controls =>true %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</table>
<br>

<%= link_to 'New Adventure', new_user_adventure_path(current_user) %>

app/views/adventures/new.html.erb
<h1>New Adventure</h1>
<%= form_for @adventure, url: user_adventures_path, html: {multipart: true} do |f| %>

<%= render 'form' %>
<% end %>

app/views/adventures/show.html.erb
<%= image_tag @adventure.image.url(:thumb) %>

<%= video_tag @adventure.video_url.to_s, :controls =>true %>


<p>
  <strong>Title:</strong>
  <%= @adventure.title %>
</p>

<p>
  <strong>Place:</strong>
  <%= @adventure.place %>
</p>
<p>
  <strong>Description:</strong>
  <%= @adventure.description %>
</p>


<h4>Comments</h4>
  <div id="comments">
  	<%= render :partial => "comments/comment" %>
  </div>
    <%= form_for [@adventure, Comment.new] do |f| %>
        <div class="field">
          <%= f.label :body %><br>
          <%= f.text_area :body %><br>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>
  </div>
</div>


<%= link_to 'Edit', edit_user_adventure_path %>  |
<%= link_to 'Back', user_adventures_path %>

app/views/comments/_comment.html.erb
<% @adventure.comments.each do |comment| %>
  <%= comment.body %></br>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <div class="field">
    <%= f.label :Body %><br>
    <%= f.text_area :body %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Comment', new_comment_path %>
<%= link_to 'New Comment', new_adventure_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'form' %>
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myadventure</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <div class='row'>
      <div class='span6'>
        <div class="nav nav-tabs">
          <li><%= link_to 'Home', root_path %></li>
          <% if signed_in? %>  
            <li><%= link_to 'Users', users_path %></li>
          <% end %>
          <% if signed_in? %>
            <li><%= link_to 'Setting', edit_user_path(current_user) %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
          <% else %>
            <li><%= link_to 'Sign in', user_session_path, method: 'post' %></li>
          <% end %>        
        </div>
      </div>
    </div>     
<%= yield %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>


      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class='field'>

<div class="field">

  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class='field'>
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class='field'>
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class='field'>
  <%= f.label :password_confirmation, 'Confirmation' %><br />
  <%= f.password_field :password_confirmation %>
</div>

  <div class='actions'>
    <%= f.submit %>
  </div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/users/_user.html.erb
<li> 
  <%= link_to user.email, user %>
</li>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= render 'form' %>

<%= link_to 'Show', @user %> |

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
  <h1>All users</h1>

  <ul class='users'>
    <%= render @users %>
  </ul>
>>>>>>> master

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= @user.email %>
<%= link_to 'Myadventure', user_adventures_path(current_user) %> 
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>